title: 3Blue1Brown
description: Mathematics with a distinct visual perspective. Linear algebra, calculus, neural networks, topology, and more.

baseurl: /3Blue1Brown.com

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  sass_dir: css

highlighter: rouge

plugins:
  - jekyll-feed
