title: 3Blue1Brown
description: Mathematics with a distinct visual perspective. Linear algebra, calculus, neural networks, topology, and more.
baseurl: /3Blue1Brown.com

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  posts:
    output: true

permalink: /lessons/:title:output_ext

sass:
  sass_dir: css

highlighter: rouge

theme: null

plugins:
  - jekyll-feed
  - jekyll-redirect-from
