[build]
command = "bun run build"
publish = "build/client"

  [build.environment]
  NODE_VERSION = "22"

[dev]
command = "bun run dev"

[[redirects]]
from = "https://3b1b.co/*"
to = "https://www.3blue1brown.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.3b1b.co/*"
to = "https://www.3blue1brown.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://3b1b.com/*"
to = "https://www.3blue1brown.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.3b1b.com/*"
to = "https://www.3blue1brown.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://3blue1brown.com/*"
to = "https://www.3blue1brown.com/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/404"
status = 404
