[build]
  publish = ".next"
  command = "yarn build"

[context.production.environment]
  GIT_LFS_ENABLED = "true"

[context.deploy-preview]
  command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"