[build]
  command = "hugo && find public/lessons -type f \\( -name '*.mp4' -or -name '*.mov' -or -name '*.png' \\) -delete"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.83.1"
  GIT_LFS_ENABLED = "true"

[context.deploy-preview]
  command = "hugo --environment preview"
