[build]
  publish = "out"
  command = "yarn build"

[context.production]
  environment = { GIT_LFS_ENABLED = "true", NODE_VERSION = "14.15.3" }

[context.deploy-preview]
  command = "yarn build"
  environment = { NODE_VERSION = "14.15.3" }
