[build]
  publish = "public"
  command = "yarn build"
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  GIT_LFS_ENABLED = "true"

[context.deploy-preview]
  command = "yarn build"
