name: Deploy live site

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build site and deploy to gh-pages branch
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "gh-pages"
