name: 3Brown1Blue

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "19.6.0"
      - run: npm ci
      - run: npm run check

  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "19.6.0"
      - run: npm ci
      - run: npm run lint