name: Test sync bucket

on:
  push:
    branches:
      - workflow

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          lfs: true         # Fetch git lfs objects
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Build
        run: hugo --environment production

      # - name: Deploy Site
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     exclude_assets: 'lessons/**/*.jpg,lessons/**/*.mp4,lessons/**/*.png'
      #     publish_dir: ./public

      - name: Sync bucket
        uses: ./.github/actions/sync
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: us-east-1
          SOURCE_DIR: 'public/'
